@extends('layouts.admin')
@section('title', 'Pengaturan Aplikasi')
@section('page-title', 'Pengaturan Aplikasi')
@section('page-subtitle', 'Sesuaikan identitas dan tampilan aplikasi Anda.')
@section('content')
<div class="settings-shell">
    @if (session('success'))<div class="alert alert-success small">{{ session('success') }}</div>@endif
    @if ($errors->any())<div class="alert alert-danger small">{{ $errors->first() }}</div>@endif
    <form method="POST" action="{{ route('admin.settings.update') }}">@csrf @method('PUT')
        <div class="row g-4">
            <div class="col-12"><div class="content-card"><div class="section-title"><span class="section-number">01</span><div><h5>Identitas aplikasi</h5><p>Nama dan informasi dasar yang tampil di seluruh halaman.</p></div></div><div class="row g-3"><div class="col-md-6"><label class="form-label">Nama aplikasi</label><input name="app_name" class="form-control" value="{{ old('app_name', $settings['app_name'] ?? '') }}" required></div><div class="col-md-6"><label class="form-label">Versi aplikasi</label><input name="app_version" class="form-control" value="{{ old('app_version', $settings['app_version'] ?? '') }}" required></div><div class="col-md-6"><label class="form-label">Tagline</label><input name="app_tagline" class="form-control" value="{{ old('app_tagline', $settings['app_tagline'] ?? '') }}"></div><div class="col-md-6"><label class="form-label">Teks footer</label><input name="footer_text" class="form-control" value="{{ old('footer_text', $settings['footer_text'] ?? '') }}" required></div></div></div></div>
            <div class="col-12"><div class="content-card"><div class="section-title"><span class="section-number">02</span><div><h5>Tampilan & warna</h5><p>Semua pengaturan visual aplikasi dikelola dari satu bagian.</p></div></div><div class="row g-3"><div class="col-md-3"><div class="layout-color-card"><div class="swatch-preview" id="primary-preview"></div><label class="form-label">Warna utama</label><div class="color-control"><input type="color" id="primary-picker" value="{{ old('primary_color', $settings['primary_color'] ?? '#6c63ff') }}"><input name="primary_color" id="primary-color" class="form-control" value="{{ old('primary_color', $settings['primary_color'] ?? '#6c63ff') }}" pattern="^#[0-9A-Fa-f]{6}$" required></div></div></div><div class="col-md-3"><div class="layout-color-card"><div class="swatch-preview" id="sidebar-preview"></div><label class="form-label">Sidebar</label><div class="color-control"><input type="color" id="sidebar-picker" value="{{ old('sidebar_color', $settings['sidebar_color'] ?? '#1f2440') }}"><input name="sidebar_color" id="sidebar-color" class="form-control" value="{{ old('sidebar_color', $settings['sidebar_color'] ?? '#1f2440') }}" pattern="^#[0-9A-Fa-f]{6}$" required></div></div></div><div class="col-md-3"><div class="layout-color-card"><div class="swatch-preview" id="navbar-preview"></div><label class="form-label">Navbar</label><div class="color-control"><input type="color" id="navbar-picker" value="{{ old('navbar_color', $settings['navbar_color'] ?? '#ffffff') }}"><input name="navbar_color" id="navbar-color" class="form-control" value="{{ old('navbar_color', $settings['navbar_color'] ?? '#ffffff') }}" pattern="^#[0-9A-Fa-f]{6}$" required></div></div></div><div class="col-md-3"><div class="layout-color-card"><div class="swatch-preview" id="footer-preview"></div><label class="form-label">Footer</label><div class="color-control"><input type="color" id="footer-picker" value="{{ old('footer_color', $settings['footer_color'] ?? '#ffffff') }}"><input name="footer_color" id="footer-color" class="form-control" value="{{ old('footer_color', $settings['footer_color'] ?? '#ffffff') }}" pattern="^#[0-9A-Fa-f]{6}$" required></div></div></div><div class="col-md-4"><label class="form-label">Tema default</label><select name="default_theme" class="form-select"><option value="light" @selected(($settings['default_theme'] ?? 'light') === 'light')>Light mode</option><option value="dark" @selected(($settings['default_theme'] ?? 'light') === 'dark')>Dark mode</option></select></div></div></div></div>
            <div class="col-12"><div class="content-card"><div class="section-title"><span class="section-number">03</span><div><h5>Kontak & regional</h5><p>Informasi pendukung untuk kebutuhan sistem.</p></div></div><div class="row g-3"><div class="col-md-6"><label class="form-label">Email kontak</label><input type="email" name="contact_email" class="form-control" value="{{ old('contact_email', $settings['contact_email'] ?? '') }}"></div><div class="col-md-6"><label class="form-label">Timezone</label><select name="timezone" class="form-select"><option value="Asia/Makassar" @selected(($settings['timezone'] ?? '') === 'Asia/Makassar')>Asia/Makassar (WITA)</option><option value="Asia/Jakarta" @selected(($settings['timezone'] ?? '') === 'Asia/Jakarta')>Asia/Jakarta (WIB)</option><option value="Asia/Jayapura" @selected(($settings['timezone'] ?? '') === 'Asia/Jayapura')>Asia/Jayapura (WIT)</option><option value="UTC" @selected(($settings['timezone'] ?? '') === 'UTC')>UTC</option></select></div></div></div></div>
            <div class="col-12"><div class="content-card google-settings-card"><div class="section-title"><span class="section-number"><i class="fab fa-google"></i></span><div><h5>Google OAuth & API</h5><p>Atur kredensial untuk login dan registrasi dengan akun Google.</p></div></div><div class="alert alert-info small"><i class="fas fa-circle-info me-2"></i>Tambahkan redirect URI berikut di Google Cloud Console: <code>{{ route('auth.google.callback') }}</code></div><div class="row g-3"><div class="col-md-6"><label class="form-label">Google Client ID</label><input name="google_client_id" class="form-control" value="{{ old('google_client_id', $settings['google_client_id'] ?? '') }}" placeholder="xxxx.apps.googleusercontent.com"></div><div class="col-md-6"><label class="form-label">Google Client Secret</label><input type="password" name="google_client_secret" class="form-control" value="{{ old('google_client_secret', $settings['google_client_secret'] ?? '') }}" placeholder="Kosongkan jika tidak diubah"></div><div class="col-md-6"><label class="form-label">Google API Key <span class="text-muted">(opsional)</span></label><input type="password" name="google_api_key" class="form-control" value="{{ old('google_api_key', $settings['google_api_key'] ?? '') }}" placeholder="AIza..."></div><div class="col-md-6"><label class="form-label">Redirect URI <span class="text-muted">(opsional)</span></label><input type="url" name="google_redirect_uri" class="form-control" value="{{ old('google_redirect_uri', $settings['google_redirect_uri'] ?? route('auth.google.callback')) }}"></div></div></div></div>
            <div class="col-12 d-flex justify-content-end"><button class="btn btn-primary px-4"><i class="fas fa-check me-2"></i>Simpan pengaturan</button></div>
        </div>
    </form>
</div>
<script>const bindColor=(picker,input,preview)=>{const p=document.getElementById(picker),i=document.getElementById(input),v=document.getElementById(preview),paint=color=>{if(v)v.style.backgroundColor=color},sync=()=>{if(/^#[0-9a-f]{6}$/i.test(i.value)){p.value=i.value;paint(i.value)}};p?.addEventListener('input',()=>{i.value=p.value;paint(p.value)});i?.addEventListener('input',sync);sync()};bindColor('primary-picker','primary-color','primary-preview');bindColor('sidebar-picker','sidebar-color','sidebar-preview');bindColor('navbar-picker','navbar-color','navbar-preview');bindColor('footer-picker','footer-color','footer-preview');</script>
@endsection
