@extends('layouts.admin')

@section('title', $pageTitle)
@section('page-title', $pageTitle)
@section('page-subtitle', 'Kelola identitas, kredensial, dan hak akses pengguna.')

@section('content')
    @php($currentRole = old('role', $user->role ?: 'user'))
    <div class="user-editor-shell">
        <div class="user-editor-banner"><div class="banner-shape shape-a"></div><div class="banner-shape shape-b"></div><div class="editor-avatar" id="editor-avatar">{{ $user->exists ? strtoupper(substr($user->name, 0, 1)) : 'U' }}</div><div class="banner-copy"><span class="eyebrow">{{ $user->exists ? 'EDIT DATA PENGGUNA' : 'PENGGUNA BARU' }}</span><h2 id="preview-name">{{ $user->exists ? $user->name : 'Pengguna baru' }}</h2><p id="preview-role">{{ ucfirst($currentRole) }} · Profil akses aplikasi</p></div><div class="banner-status"><span class="online-dot"></span> Akun aktif</div></div>

        @if ($errors->any())<div class="alert alert-danger small mt-4">{{ $errors->first() }}</div>@endif
        <form method="POST" action="{{ $user->exists ? route('admin.users.update', $user) : route('admin.users.store') }}" class="row g-4 mt-1">
            @csrf
            @if ($user->exists) @method('PUT') @endif
            <div class="col-12 col-lg-8"><div class="content-card h-100"><div class="section-title"><span class="section-number">01</span><div><h5>Informasi dasar</h5><p>Data identitas utama pengguna.</p></div></div><div class="row g-3"><div class="col-12"><label class="form-label" for="name">Nama lengkap</label><input id="name" name="name" class="form-control form-control-lg" value="{{ old('name', $user->name) }}" placeholder="Contoh: Andi Pratama" required></div><div class="col-12"><label class="form-label" for="email">Alamat email</label><div class="input-group input-group-lg"><span class="input-group-text"><i class="far fa-envelope"></i></span><input id="email" type="email" name="email" class="form-control" value="{{ old('email', $user->email) }}" placeholder="nama@perusahaan.com" required></div><div class="form-hint"><i class="fas fa-circle-info me-1"></i>Email digunakan untuk login dan reset password.</div></div></div></div></div>
            <div class="col-12 col-lg-4"><div class="content-card h-100"><div class="section-title"><span class="section-number">02</span><div><h5>Hak akses</h5><p>Pilih role pengguna.</p></div></div><div class="role-picker"><label class="role-option {{ $currentRole === 'admin' ? 'selected' : '' }}"><input type="radio" name="role" value="admin" @checked($currentRole === 'admin')><span class="role-icon role-admin"><i class="fas fa-shield-halved"></i></span><span><strong>Admin</strong><small>Akses penuh aplikasi</small></span><i class="fas fa-check-circle check"></i></label><label class="role-option {{ $currentRole === 'manager' ? 'selected' : '' }}"><input type="radio" name="role" value="manager" @checked($currentRole === 'manager')><span class="role-icon role-manager"><i class="fas fa-briefcase"></i></span><span><strong>Manager</strong><small>Kelola operasional</small></span><i class="fas fa-check-circle check"></i></label><label class="role-option {{ $currentRole === 'user' ? 'selected' : '' }}"><input type="radio" name="role" value="user" @checked($currentRole === 'user')><span class="role-icon role-user"><i class="fas fa-user"></i></span><span><strong>User</strong><small>Akses dasar aplikasi</small></span><i class="fas fa-check-circle check"></i></label></div></div></div>
            <div class="col-12"><div class="content-card"><div class="section-title"><span class="section-number">03</span><div><h5>{{ $user->exists ? 'Keamanan akun' : 'Buat password' }}</h5><p>{{ $user->exists ? 'Kosongkan jika password tidak ingin diubah.' : 'Password digunakan pengguna untuk login.' }}</p></div></div><div class="row g-3"><div class="col-md-6"><label class="form-label" for="password">Password {{ $user->exists ? '(opsional)' : '' }}</label><div class="password-field"><input id="password" type="password" name="password" class="form-control" minlength="8" {{ $user->exists ? '' : 'required' }} placeholder="Minimal 8 karakter"><button type="button" class="password-toggle"><i class="far fa-eye"></i></button></div></div><div class="col-md-6"><label class="form-label" for="password_confirmation">Konfirmasi password</label><input id="password_confirmation" type="password" name="password_confirmation" class="form-control" minlength="8" {{ $user->exists ? '' : 'required' }} placeholder="Ulangi password"></div></div></div></div>
            <div class="col-12 d-flex justify-content-end gap-2"><a href="{{ route('admin.users') }}" class="btn btn-light px-4">Batal</a><button class="btn btn-primary px-4"><i class="fas fa-check me-2"></i>{{ $user->exists ? 'Simpan perubahan' : 'Buat pengguna' }}</button></div>
        </form>
    </div>
    <script>document.querySelectorAll('.role-option input').forEach(input=>input.addEventListener('change',()=>{document.querySelectorAll('.role-option').forEach(x=>x.classList.remove('selected'));input.closest('.role-option').classList.add('selected');document.getElementById('preview-role').textContent=input.value.charAt(0).toUpperCase()+input.value.slice(1)+' · Profil akses aplikasi'}));document.getElementById('name')?.addEventListener('input',e=>{let n=e.target.value.trim()||'Pengguna baru';document.getElementById('preview-name').textContent=n;document.getElementById('editor-avatar').textContent=n.charAt(0).toUpperCase()});document.querySelector('.password-toggle')?.addEventListener('click',e=>{let i=document.getElementById('password');i.type=i.type==='password'?'text':'password';e.currentTarget.innerHTML=i.type==='password'?'<i class="far fa-eye"></i>':'<i class="far fa-eye-slash"></i>'});document.getElementById('avatar')?.addEventListener('change',()=>document.getElementById('avatar-submit')?.click());</script>
@endsection
