@extends('layouts.admin')

@section('title', 'Profil Pengguna')
@section('page-title', 'Profil Pengguna')
@section('page-subtitle', 'Profil profesional dan pengaturan keamanan akun Anda.')

@section('content')
    @if (session('success'))<div class="alert alert-success small">{{ session('success') }}</div>@endif
    @if ($errors->any())<div class="alert alert-danger small">{{ $errors->first() }}</div>@endif

    <div class="cv-header content-card mb-4">
        <div class="profile-avatar cv-avatar">
            @if (auth()->user()->avatar)<img src="{{ asset('storage/'.auth()->user()->avatar) }}" alt="Avatar">@else{{ strtoupper(substr(auth()->user()->name, 0, 1)) }}@endif
        </div>
        <div class="cv-intro"><p class="eyebrow mb-2">PROFIL PROFESIONAL</p><h2>{{ auth()->user()->name }}</h2><p class="cv-role">{{ auth()->user()->job_title ?: ucfirst(auth()->user()->role) }}</p><p class="cv-bio">{{ auth()->user()->bio ?: 'Tambahkan ringkasan singkat tentang diri Anda untuk melengkapi profil.' }}</p><div class="cv-meta"><span><i class="fas fa-location-dot"></i>{{ auth()->user()->location ?: 'Lokasi belum diisi' }}</span><span><i class="fas fa-envelope"></i>{{ auth()->user()->email }}</span><span><i class="fas fa-phone"></i>{{ auth()->user()->phone ?: 'Telepon belum diisi' }}</span></div></div>
        <div class="cv-actions"><form method="POST" action="{{ route('profile.avatar') }}" enctype="multipart/form-data"><input type="file" name="avatar" id="avatar" class="d-none" accept="image/*" required><label for="avatar" class="btn btn-light btn-sm"><i class="fas fa-camera me-1"></i> Ganti avatar</label><button class="d-none" id="avatar-submit"></button></form></div>
    </div>

    <ul class="nav nav-pills profile-tabs mb-4" role="tablist"><li class="nav-item"><button class="nav-link active" data-bs-toggle="pill" data-bs-target="#overview" type="button">Ringkasan CV</button></li><li class="nav-item"><button class="nav-link" data-bs-toggle="pill" data-bs-target="#security" type="button">Ubah Password</button></li><li class="nav-item"><button class="nav-link" data-bs-toggle="pill" data-bs-target="#sessions" type="button">Sesi Aktif <span class="badge text-bg-light">{{ $sessions->count() }}</span></button></li></ul>

    <div class="tab-content">
        <div class="tab-pane fade show active" id="overview">
            <div class="row g-4"><div class="col-12 col-lg-8"><div class="content-card"><div class="card-heading"><div><h5>Tentang saya</h5><p>Informasi singkat mengenai profil Anda.</p></div></div><p class="text-muted small lh-lg">{{ auth()->user()->bio ?: 'Belum ada deskripsi. Ceritakan pengalaman, keahlian, atau fokus pekerjaan Anda.' }}</p></div></div><div class="col-12 col-lg-4"><div class="content-card"><div class="card-heading"><div><h5>Informasi kontak</h5><p>Data pribadi umum.</p></div></div><dl class="row small mb-0"><dt class="col-5 text-muted">Jabatan</dt><dd class="col-7">{{ auth()->user()->job_title ?: '-' }}</dd><dt class="col-5 text-muted">Tanggal lahir</dt><dd class="col-7">{{ auth()->user()->birth_date ? date('d M Y', strtotime(auth()->user()->birth_date)) : '-' }}</dd><dt class="col-5 text-muted">Website</dt><dd class="col-7 text-break">{{ auth()->user()->website ?: '-' }}</dd><dt class="col-5 text-muted">Bergabung</dt><dd class="col-7">{{ auth()->user()->created_at->format('M Y') }}</dd></dl></div></div></div>
            <div class="content-card mt-4"><div class="card-heading"><div><h5>Edit informasi profil</h5><p>Lengkapi informasi umum agar profil Anda lebih personal.</p></div></div><form method="POST" action="{{ route('profile.update') }}">@csrf @method('PUT')<div class="row g-3"><div class="col-md-6"><label class="form-label">Nama lengkap</label><input name="name" class="form-control" value="{{ old('name', auth()->user()->name) }}" required></div><div class="col-md-6"><label class="form-label">Alamat email</label><input type="email" name="email" class="form-control" value="{{ old('email', auth()->user()->email) }}" required></div><div class="col-md-6"><label class="form-label">Jabatan / profesi</label><input name="job_title" class="form-control" value="{{ old('job_title', auth()->user()->job_title) }}" placeholder="Contoh: Product Manager"></div><div class="col-md-6"><label class="form-label">Nomor telepon</label><input name="phone" class="form-control" value="{{ old('phone', auth()->user()->phone) }}" placeholder="08xxxxxxxxxx"></div><div class="col-md-6"><label class="form-label">Lokasi</label><input name="location" class="form-control" value="{{ old('location', auth()->user()->location) }}" placeholder="Kota, Negara"></div><div class="col-md-6"><label class="form-label">Tanggal lahir</label><input type="date" name="birth_date" class="form-control" value="{{ old('birth_date', auth()->user()->birth_date) }}"></div><div class="col-12"><label class="form-label">Website</label><input type="url" name="website" class="form-control" value="{{ old('website', auth()->user()->website) }}" placeholder="https://website-anda.com"></div><div class="col-12"><label class="form-label">Bio singkat</label><textarea name="bio" class="form-control" rows="4" maxlength="1000" placeholder="Tuliskan ringkasan singkat tentang diri Anda...">{{ old('bio', auth()->user()->bio) }}</textarea></div></div><button class="btn btn-primary mt-4">Simpan profil</button></form></div>
        </div>
        <div class="tab-pane fade" id="security"><div class="content-card col-12 col-lg-7"><h5 class="fw-bold">Ubah password</h5><p class="text-muted small mb-4">Gunakan password minimal 8 karakter. Sesi perangkat lain akan dihentikan setelah password diubah.</p><form method="POST" action="{{ route('password.change.update') }}">@csrf @method('PUT')<label class="form-label">Password saat ini</label><input type="password" name="current_password" class="form-control mb-3" required><label class="form-label">Password baru</label><input type="password" name="password" class="form-control mb-3" minlength="8" required><label class="form-label">Konfirmasi password baru</label><input type="password" name="password_confirmation" class="form-control mb-4" required><button class="btn btn-primary">Ubah password</button></form></div></div>
        <div class="tab-pane fade" id="sessions"><div class="content-card"> <div class="card-heading"><div><h5>Sesi aktif</h5><p>Perangkat yang sedang login ke akun Anda.</p></div><button class="btn btn-outline-danger btn-sm" data-bs-toggle="modal" data-bs-target="#revokeModal">Hentikan sesi lain</button></div><div class="table-responsive"><table class="table align-middle"><thead><tr><th>PERANGKAT / IP</th><th>AKTIVITAS TERAKHIR</th><th></th></tr></thead><tbody>@forelse ($sessions as $session)<tr><td><strong>{{ $session->user_agent ? \Illuminate\Support\Str::limit($session->user_agent, 70) : 'Perangkat tidak dikenal' }}</strong><small class="d-block text-muted">{{ $session->ip_address }} @if ($session->id === request()->session()->getId()) · <span class="text-success">Sesi ini</span>@endif</small></td><td class="text-muted">{{ date('d M Y H:i', $session->last_activity) }}</td><td class="text-end">@if ($session->id !== request()->session()->getId())<form method="POST" action="{{ route('sessions.revoke', $session->id) }}" data-confirm="Hentikan sesi pada perangkat ini?">@csrf @method('DELETE')<button class="btn btn-sm btn-light text-danger">Hentikan</button></form>@endif</td></tr>@empty<tr><td colspan="3" class="text-muted">Belum ada sesi tersimpan.</td></tr>@endforelse</tbody></table></div></div></div>
    </div>
    <div class="modal fade" id="revokeModal" tabindex="-1"><div class="modal-dialog"><div class="modal-content"><form method="POST" action="{{ route('sessions.revoke-others') }}">@csrf @method('DELETE')<div class="modal-header"><h5 class="modal-title">Hentikan sesi lain</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><label class="form-label">Konfirmasi password</label><input type="password" name="password" class="form-control" required></div><div class="modal-footer"><button type="button" class="btn btn-light" data-bs-dismiss="modal">Batal</button><button class="btn btn-danger">Hentikan semua</button></div></form></div></div></div>
    <script>document.getElementById('avatar')?.addEventListener('change',()=>document.getElementById('avatar-submit')?.click());</script>
@endsection
