@extends('layouts.admin')
@section('title', $invitation->exists ? 'Edit Undangan' : 'Buat Undangan')
@section('page-title', $invitation->exists ? 'Edit Undangan' : 'Buat Undangan')
@section('page-subtitle', 'Atur template, isi, dan bagian yang ingin ditampilkan pada undangan Anda.')
@section('content')
<form method="POST" action="{{ $invitation->exists ? route('invitations.update', $invitation) : route('invitations.store') }}">
    @csrf @if($invitation->exists) @method('PUT') @endif
    <div class="row g-4"><div class="col-12 col-xl-8">
        <div class="content-card mb-4"><div class="card-heading"><div><h5>Informasi Undangan</h5><p>Nama dan link publik undangan.</p></div></div><div class="row g-3 p-3 pt-0"><div class="col-md-7"><label class="form-label">Nama undangan</label><input name="title" value="{{ old('title', $invitation->title) }}" class="form-control" placeholder="Contoh: Pernikahan Adit & Ayu" required></div><div class="col-md-5"><label class="form-label">Slug link</label><div class="input-group"><span class="input-group-text">/undangan/</span><input name="slug" value="{{ old('slug', $invitation->slug) }}" class="form-control" placeholder="adit-ayu" required></div><small class="text-muted">Gunakan huruf, angka, atau tanda hubung.</small></div></div></div>
        <div class="content-card mb-4"><div class="card-heading"><div><h5>Isi Undangan</h5><p>Semua teks di bawah ini dapat Anda sesuaikan.</p></div></div><div class="row g-3 p-3 pt-0"><div class="col-md-6"><label class="form-label">Nama mempelai pria</label><input name="content[groom_name]" value="{{ old('content.groom_name', data_get($invitation->content, 'groom_name')) }}" class="form-control" required></div><div class="col-md-6"><label class="form-label">Nama mempelai wanita</label><input name="content[bride_name]" value="{{ old('content.bride_name', data_get($invitation->content, 'bride_name')) }}" class="form-control" required></div><div class="col-md-6"><label class="form-label">Tanggal acara</label><input type="date" name="content[date]" value="{{ old('content.date', data_get($invitation->content, 'date')) }}" class="form-control" required></div><div class="col-md-6"><label class="form-label">Waktu acara</label><input name="content[time]" value="{{ old('content.time', data_get($invitation->content, 'time')) }}" class="form-control" placeholder="10:00 - selesai" required></div><div class="col-md-6"><label class="form-label">Nama tempat</label><input name="content[venue]" value="{{ old('content.venue', data_get($invitation->content, 'venue')) }}" class="form-control" required></div><div class="col-md-6"><label class="form-label">Alamat acara</label><input name="content[address]" value="{{ old('content.address', data_get($invitation->content, 'address')) }}" class="form-control" required></div><div class="col-12"><label class="form-label">Pesan pembuka</label><textarea name="content[hero_message]" rows="2" class="form-control">{{ old('content.hero_message', data_get($invitation->content, 'hero_message')) }}</textarea></div><div class="col-12"><label class="form-label">Kisah kami</label><textarea name="content[story]" rows="4" class="form-control">{{ old('content.story', data_get($invitation->content, 'story')) }}</textarea></div><div class="col-12"><label class="form-label">Link RSVP (opsional)</label><input type="url" name="content[rsvp_url]" value="{{ old('content.rsvp_url', data_get($invitation->content, 'rsvp_url')) }}" class="form-control" placeholder="https://forms.google.com/..."></div></div></div>
    </div><div class="col-12 col-xl-4">
        <div class="content-card mb-4"><div class="card-heading"><div><h5>Pilih Template</h5><p>Pilih gaya visual dan lihat preview sebelum digunakan.</p></div></div><div class="p-3 pt-0 d-grid gap-2">@foreach($templates as $key => $template)<div class="template-option-row"><label class="template-option flex-grow-1"><input type="radio" name="template" value="{{ $key }}" {{ old('template', $invitation->template) === $key ? 'checked' : '' }}><span><strong>{{ $template['name'] }}</strong><small>{{ $template['description'] }}</small></span></label><a href="{{ $template['preview_url'] }}" target="_blank" class="btn btn-sm btn-outline-secondary template-preview-link" title="Preview template"><i class="fas fa-eye"></i></a></div>@endforeach</div></div>
        <div class="content-card mb-4"><div class="card-heading"><div><h5>Bagian Undangan</h5><p>Aktifkan bagian yang ingin ditampilkan.</p></div></div><div class="p-3 pt-0 d-grid gap-2">@foreach($sectionLabels as $key => $label)<label class="section-toggle"><input type="checkbox" name="sections[]" value="{{ $key }}" {{ in_array($key, old('sections', $invitation->sections ?? []), true) ? 'checked' : '' }}><span>{{ $label }}</span></label>@endforeach</div></div>
        <div class="d-grid gap-2">@if($invitation->exists)<a href="{{ route('invitations.preview', $invitation) }}" target="_blank" class="btn btn-outline-secondary"><i class="fas fa-eye me-2"></i>Preview Undangan</a>@endif<button class="btn btn-primary btn-lg"><i class="fas fa-save me-2"></i>Simpan Undangan</button>@if($invitation->exists)<button form="publish-form" class="btn btn-outline-{{ $invitation->is_published ? 'warning' : 'success' }}">{{ $invitation->is_published ? 'Sembunyikan dari Publik' : 'Publikasikan Undangan' }}</button>@endif<a href="{{ route('invitations.index') }}" class="btn btn-light">Batal</a></div>
    </div></div>
</form>
@if($invitation->exists)<form id="publish-form" method="POST" action="{{ route('invitations.publish', $invitation) }}">@csrf @method('PATCH')</form>@endif
@endsection
