@extends('layouts.admin')
@section('title', 'Undangan Saya')
@section('page-title', 'Undangan Saya')
@section('page-subtitle', 'Buat undangan digital dengan tampilan dan link yang Anda tentukan sendiri.')
@section('content')
<div class="d-flex justify-content-end mb-4"><a href="{{ route('invitations.create') }}" class="btn btn-primary"><i class="fas fa-plus me-2"></i>Buat Undangan</a></div>
<div class="row g-4">
    @forelse($invitations as $invitation)
        @php($template = $templates[$invitation->template] ?? $templates['classic'])
        <div class="col-12 col-md-6 col-xl-4"><div class="content-card h-100 invitation-card"><div class="invitation-card-preview" style="--invitation-accent: {{ $template['accent'] }}"><span>{{ $template['name'] }}</span><strong>{{ $invitation->content['groom_name'] ?? 'Nama' }} &amp; {{ $invitation->content['bride_name'] ?? 'Pasangan' }}</strong></div><div class="p-3"><div class="d-flex justify-content-between align-items-start gap-2"><div><h5 class="mb-1">{{ $invitation->title }}</h5><small class="text-muted">{{ $invitation->is_published ? 'Dipublikasikan' : 'Draft' }} · {{ $template['name'] }}</small></div><span class="badge {{ $invitation->is_published ? 'text-bg-success' : 'text-bg-secondary' }}">{{ $invitation->is_published ? 'Live' : 'Draft' }}</span></div><div class="d-flex justify-content-between align-items-center mt-3"><small class="text-muted"><i class="fas fa-reply me-1"></i>{{ $invitation->rsvps_count }} RSVP</small><a href="{{ route('invitations.rsvps', $invitation) }}" class="small text-decoration-none">Lihat respons</a></div><div class="d-flex gap-2 mt-3"><a href="{{ route('invitations.edit', $invitation) }}" class="btn btn-sm btn-primary flex-fill"><i class="fas fa-pen me-1"></i>Edit</a><a href="{{ route('invitations.preview', $invitation) }}" target="_blank" class="btn btn-sm btn-outline-secondary" title="Preview"><i class="fas fa-eye"></i></a><form method="POST" action="{{ route('invitations.publish', $invitation) }}">@csrf @method('PATCH')<button class="btn btn-sm btn-outline-{{ $invitation->is_published ? 'warning' : 'success' }}" title="{{ $invitation->is_published ? 'Sembunyikan' : 'Publikasikan' }}"><i class="fas fa-{{ $invitation->is_published ? 'eye-slash' : 'globe' }}"></i></button></form>@if($invitation->is_published)<a href="{{ route('invitations.public', $invitation->slug) }}" target="_blank" class="btn btn-sm btn-outline-secondary" title="Link publik"><i class="fas fa-external-link-alt"></i></a>@endif<form method="POST" action="{{ route('invitations.destroy', $invitation) }}" data-confirm="Hapus undangan ini?"><button class="btn btn-sm btn-outline-danger" title="Hapus"><i class="fas fa-trash"></i></button>@csrf @method('DELETE')</form></div></div></div></div>
    @empty
        <div class="col-12"><div class="content-card text-center py-5"><div class="empty-invitation-icon"><i class="fas fa-envelope-open-text"></i></div><h4>Belum ada undangan</h4><p class="text-muted mb-4">Mulai buat undangan pertama Anda dan bagikan link-nya kepada tamu.</p><a href="{{ route('invitations.create') }}" class="btn btn-primary"><i class="fas fa-plus me-2"></i>Buat Undangan Pertama</a></div></div>
    @endforelse
</div>
@endsection
